name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    - name: clang
      run: sudo apt-get update && sudo apt-get install -yq clang
    # mov headers
    - name: move headers
      run: mv belegpp.h belegpp_sf.h tests
    # run tests
    - name: build
      run: cd tests && clang++ tests.cpp -std=c++17 -o a.out
    - name: run test
      run: cd tests && ./a.out